/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Tania
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    String nombreCompletoEmpleadoActual;

    public String getNombreCompletoEmpleadoActual() {
        return nombreCompletoEmpleadoActual;
    }

    public void setNombreCompletoEmpleadoActual(String nombreCompletoEmpleadoActual) {
        this.nombreCompletoEmpleadoActual = nombreCompletoEmpleadoActual;
    }
    
    
    
    public ventanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuerpo = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JPanel();
        iconoEmpleado = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JPanel();
        iconoUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        panelPie = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelCuerpo.setBackground(new java.awt.Color(181, 121, 176));
        panelCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpleados.setBackground(new java.awt.Color(99, 20, 92));
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmpleadosMousePressed(evt);
            }
        });
        btnEmpleados.setLayout(new java.awt.GridLayout(0, 1));

        iconoEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Employee_32px.png"))); // NOI18N
        iconoEmpleado.setToolTipText("");
        iconoEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmpleadosMousePressed(evt);
            }
        });
        btnEmpleados.add(iconoEmpleado);

        lblEmpleado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpleado.setText("EMPLEADOS");
        lblEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmpleadosMousePressed(evt);
            }
        });
        btnEmpleados.add(lblEmpleado);

        panelCuerpo.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 130, 110));

        btnUsuarios.setBackground(new java.awt.Color(99, 20, 92));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
        });
        btnUsuarios.setLayout(new java.awt.GridLayout(0, 1));

        iconoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_User_32px.png"))); // NOI18N
        iconoUsuario.setToolTipText("");
        iconoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconoUsuariolblEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconoUsuariolblEmpleadoMouseExited(evt);
            }
        });
        btnUsuarios.add(iconoUsuario);

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("USUARIOS");
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuarioMouseExited(evt);
            }
        });
        btnUsuarios.add(lblUsuario);

        panelCuerpo.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 130, 110));

        getContentPane().add(panelCuerpo, java.awt.BorderLayout.CENTER);

        panelTitulo.setBackground(new java.awt.Color(123, 42, 116));

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Payroll_64px.png"))); // NOI18N
        lblTitulo.setText("Gestión de nomina");

        lblUsuarioActual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUsuarioActual.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioActual.setText("Haz iniciado sesión como: Carlos Moreno");
        lblUsuarioActual.setToolTipText("");

        btnCerrarSesion.setFont(new java.awt.Font("Antipasto Pro ", 1, 12)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Sign_Out_32px.png"))); // NOI18N
        btnCerrarSesion.setToolTipText("Salir");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(132, 132, 132)
                .addComponent(lblUsuarioActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addGap(554, 554, 554))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addGroup(panelTituloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsuarioActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        panelPie.setBackground(new java.awt.Color(123, 42, 116));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Todos los derechos reservados ©");
        panelPie.add(jLabel4);

        getContentPane().add(panelPie, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(928, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseEntered
        setColor(btnEmpleados);
    }//GEN-LAST:event_btnEmpleadosMouseEntered

    private void btnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseExited
        resetColor(btnEmpleados);
    }//GEN-LAST:event_btnEmpleadosMouseExited

    private void lblEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpleadoMouseEntered
        setColor(btnEmpleados);
    }//GEN-LAST:event_lblEmpleadoMouseEntered

    private void lblEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpleadoMouseExited
        resetColor(btnEmpleados);
    }//GEN-LAST:event_lblEmpleadoMouseExited

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        setColor(btnUsuarios);
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        resetColor(btnUsuarios);
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void iconoUsuariolblEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoUsuariolblEmpleadoMouseEntered
        setColor(btnUsuarios);
    }//GEN-LAST:event_iconoUsuariolblEmpleadoMouseEntered

    private void iconoUsuariolblEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoUsuariolblEmpleadoMouseExited
        resetColor(btnUsuarios);
    }//GEN-LAST:event_iconoUsuariolblEmpleadoMouseExited

    private void lblUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseEntered
        setColor(btnUsuarios);
    }//GEN-LAST:event_lblUsuarioMouseEntered

    private void lblUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMouseExited
        resetColor(btnUsuarios);
    }//GEN-LAST:event_lblUsuarioMouseExited

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        new ventanaInicioSesion().show();
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMousePressed
               
        ventanaEmpleados e = new ventanaEmpleados();
        this.dispose();
    }//GEN-LAST:event_btnEmpleadosMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblUsuarioActual.setText("Haz iniciado sesión como: " + getNombreCompletoEmpleadoActual());
    }//GEN-LAST:event_formWindowOpened

    public void setColor(JPanel panel) {
        panel.setBackground(new Color(123, 42, 116));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(99, 20, 92));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ventanaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JPanel btnEmpleados;
    private javax.swing.JPanel btnUsuarios;
    private javax.swing.JLabel iconoEmpleado;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelPie;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
